
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Menu_Principal extends javax.swing.JFrame {

    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jp_ModCliente = new javax.swing.JPopupMenu();
        jmi_Mod = new javax.swing.JMenuItem();
        jp_ModElOrden = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_NombreC = new javax.swing.JTextField();
        tf_NumeroDTele = new javax.swing.JTextField();
        tf_Efectivo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_Direccion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_ListaClientes = new javax.swing.JList<>();
        jb_GCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        cb_Cliente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jb_binaria = new javax.swing.JButton();
        jb_especial = new javax.swing.JButton();
        jb_reloaded = new javax.swing.JButton();
        jb_out = new javax.swing.JButton();
        jb_TerminarOrden = new javax.swing.JButton();
        jb_ComenzarOrden = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_Ordenes = new javax.swing.JTree();
        jLabel12 = new javax.swing.JLabel();

        jScrollPane6.setViewportView(jTree1);

        jmi_Mod.setText("Modificar cliente");
        jmi_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ModActionPerformed(evt);
            }
        });
        jp_ModCliente.add(jmi_Mod);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAS BALEADAS BINARIAS");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel6.setText("Clientes:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Numero de telefono:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Efectivo que lleva:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Direccion");

        ta_Direccion.setColumns(13);
        ta_Direccion.setRows(6);
        jScrollPane5.setViewportView(ta_Direccion);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel11.setText("Lista de clientes:");

        jl_ListaClientes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jl_ListaClientes.setModel(new DefaultListModel());
        jl_ListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ListaClientesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jl_ListaClientes);

        jb_GCliente.setText("Guardar Cliente");
        jb_GCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tf_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_NumeroDTele))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Efectivo)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addComponent(jb_GCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel11)
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_NumeroDTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_Efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jb_GCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("Menu de Baleadas Binarias:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Baleadas Binarias L.22");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Baleadas especiales L.35");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Baleadas Reloaded L.55");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Baleadas OutOfBounds L.85");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(10);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Ingredientes:\n-Tortilla\n-Frijoles\n-Mantequilla\n");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(10);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Ingredientes:\n-Tortilla\n-Frijoles\n-Mantequilla\n-Huevo\n");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Ingredientes:\n-Tortilla\n-Frijoles\n-Mantequilla\n-Huevo\n-Platano\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(10);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Ingredientes:\n-Tortilla\n-Frijoles\n-Mantequilla\n-Huevo\n-Platano\n-Chorizo");
        jScrollPane4.setViewportView(jTextArea4);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel13.setText("Elija su Cliente antes de ordenar");

        jb_binaria.setText("Ordenar Binaria");
        jb_binaria.setEnabled(false);
        jb_binaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_binariaMouseClicked(evt);
            }
        });

        jb_especial.setText("Ordenar Especial");
        jb_especial.setEnabled(false);
        jb_especial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_especialMouseClicked(evt);
            }
        });

        jb_reloaded.setText("Ordenar Reloaded");
        jb_reloaded.setEnabled(false);
        jb_reloaded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_reloadedMouseClicked(evt);
            }
        });

        jb_out.setText("Ordenar OutOfBound");
        jb_out.setEnabled(false);
        jb_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_outMouseClicked(evt);
            }
        });

        jb_TerminarOrden.setText("Terminar Orden");
        jb_TerminarOrden.setEnabled(false);
        jb_TerminarOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_TerminarOrdenMouseClicked(evt);
            }
        });

        jb_ComenzarOrden.setText("Comenzar Orden");
        jb_ComenzarOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ComenzarOrdenMouseClicked(evt);
            }
        });

        jLabel14.setText("Presione Comenzar para ordenar y Terminar para agregar la orden al Tree");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jb_binaria)
                                        .addGap(36, 36, 36)
                                        .addComponent(jb_especial)
                                        .addGap(32, 32, 32)
                                        .addComponent(jb_reloaded))
                                    .addComponent(cb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_out)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jb_ComenzarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jb_TerminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel14)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_binaria)
                    .addComponent(jb_especial)
                    .addComponent(jb_reloaded)
                    .addComponent(jb_out))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_TerminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ComenzarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel14))
        );

        jTabbedPane1.addTab("Menu", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Ordenes:");
        jt_Ordenes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(jt_Ordenes);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel12.setText("Ordenes:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 242, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordenes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_GClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GClienteMouseClicked
        String Nombre = tf_NombreC.getText();
        String NumeroDTele = tf_NumeroDTele.getText();
        double Efectivo = Double.parseDouble(tf_Efectivo.getText());
        String Direccion = ta_Direccion.getText();
        
        Clientes x = new Clientes(Nombre,NumeroDTele,Efectivo,Direccion);
        DefaultListModel modelo = (DefaultListModel)jl_ListaClientes.getModel();
        modelo.addElement(x);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_Cliente.getModel();
        model.addElement(x);
        
        
        tf_NombreC.setText("");
        tf_NumeroDTele.setText("");
        tf_Efectivo.setText("");
        ta_Direccion.setText("");
        
    }//GEN-LAST:event_jb_GClienteMouseClicked

    private void jl_ListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ListaClientesMouseClicked
        if(evt.isMetaDown()){
            jp_ModCliente.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_ListaClientesMouseClicked

    private void jmi_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ModActionPerformed
        if(jl_ListaClientes.getSelectedIndex() >= 0){
        String Nombre = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre");
        String NumeroDTele = JOptionPane.showInputDialog(this,"Ingrese el nuevo numero de telefono");
        double Efectivo = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese la cantidad de efectivo que carga"));
        String Direccion = JOptionPane.showInputDialog(this, "Ingrese la direccion");
        DefaultListModel m = (DefaultListModel) jl_ListaClientes.getModel();
        Clientes cliente = new Clientes(Nombre,NumeroDTele,Efectivo,Direccion);
        m.set(jl_ListaClientes.getSelectedIndex(),cliente);
        DefaultComboBoxModel mcb = (DefaultComboBoxModel) cb_Cliente.getModel();
        mcb.insertElementAt(cliente, jl_ListaClientes.getSelectedIndex());
        mcb.removeElementAt(jl_ListaClientes.getSelectedIndex() + 1);
        }else{
            JOptionPane.showMessageDialog(this, "No hay cliente seleccionado");
        }
        
    }//GEN-LAST:event_jmi_ModActionPerformed

    private void jb_binariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_binariaMouseClicked
        if(cb_Cliente.getSelectedIndex() >= 0){
        DefaultComboBoxModel m  = (DefaultComboBoxModel)cb_Cliente.getModel();
        ((Clientes)m.getSelectedItem()).getBaleadasComprar().add(new Baleadas("Baleada Binaria","Tortilla,Mantequilla,Frijoles",22));
        }else{
            JOptionPane.showMessageDialog(this, "NO HAY CLIENTE SELECCIONADO O NO HAY CLIENTES");
        }
    }//GEN-LAST:event_jb_binariaMouseClicked

    private void jb_especialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_especialMouseClicked
        if(cb_Cliente.getSelectedIndex() >= 0){
        DefaultComboBoxModel m  = (DefaultComboBoxModel)cb_Cliente.getModel();
        ((Clientes)m.getSelectedItem()).getBaleadasComprar().add(new Baleadas("Baleada Especial","Tortilla,Mantequilla,Frijoles,Huevo",22));
        }else{
            JOptionPane.showMessageDialog(this, "NO HAY NADIE SLECCIONADO O NO HAY CLIENTES");
        }
    }//GEN-LAST:event_jb_especialMouseClicked

    private void jb_reloadedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reloadedMouseClicked
        if(cb_Cliente.getSelectedIndex() >= 0){
        DefaultComboBoxModel m  = (DefaultComboBoxModel)cb_Cliente.getModel();
        ((Clientes)m.getSelectedItem()).getBaleadasComprar().add(new Baleadas("Baleada Reloaded","Tortilla,Mantequilla,Frijoles,Huevo,Platano",22));
        }else{
            JOptionPane.showMessageDialog(this, "NO HAY NADIE SELECCIONADO O NO HAY CLIENTES");
        }
    }//GEN-LAST:event_jb_reloadedMouseClicked

    private void jb_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_outMouseClicked
        if(cb_Cliente.getSelectedIndex() >= 0){
        DefaultComboBoxModel m  = (DefaultComboBoxModel)cb_Cliente.getModel();
        ((Clientes)m.getSelectedItem()).getBaleadasComprar().add(new Baleadas("Baleada OutOfbound","Tortilla,Mantequilla,Frijoles,Huevo,Platano,Chorizo",22));
        }else{
            JOptionPane.showMessageDialog(this, "NO HAY CLIENTES SELECCIONADOS O NO HAY CLIENTES");
        }
    }//GEN-LAST:event_jb_outMouseClicked

    private void jb_TerminarOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_TerminarOrdenMouseClicked
        jb_binaria.setEnabled(false);
        jb_especial.setEnabled(false);
        jb_reloaded.setEnabled(false);
        jb_out.setEnabled(false);
        jb_TerminarOrden.setEnabled(false);
        jb_ComenzarOrden.setEnabled(true);
    }//GEN-LAST:event_jb_TerminarOrdenMouseClicked

    private void jb_ComenzarOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ComenzarOrdenMouseClicked
        jb_binaria.setEnabled(true);
        jb_especial.setEnabled(true);
        jb_reloaded.setEnabled(true);
        jb_out.setEnabled(true);
        jb_TerminarOrden.setEnabled(true);
        DefaultTreeModel modelo = (DefaultTreeModel)jt_Ordenes.getModel();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultComboBoxModel CModel = (DefaultComboBoxModel) cb_Cliente.getModel();
        DefaultMutableTreeNode OrdenJT = new DefaultMutableTreeNode(Orden);
        DefaultMutableTreeNode persona = new DefaultMutableTreeNode(((Clientes)CModel.getSelectedItem()).getNombre());
        OrdenJT.add(persona);
        nodo.add(OrdenJT);
        modelo.reload();
        Orden += 7;
        jb_ComenzarOrden.setEnabled(false);
        
    }//GEN-LAST:event_jb_ComenzarOrdenMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jb_ComenzarOrden;
    private javax.swing.JButton jb_GCliente;
    private javax.swing.JButton jb_TerminarOrden;
    private javax.swing.JButton jb_binaria;
    private javax.swing.JButton jb_especial;
    private javax.swing.JButton jb_out;
    private javax.swing.JButton jb_reloaded;
    private javax.swing.JList<String> jl_ListaClientes;
    private javax.swing.JMenuItem jmi_Mod;
    private javax.swing.JPopupMenu jp_ModCliente;
    private javax.swing.JPopupMenu jp_ModElOrden;
    private javax.swing.JTree jt_Ordenes;
    private javax.swing.JTextArea ta_Direccion;
    private javax.swing.JTextField tf_Efectivo;
    private javax.swing.JTextField tf_NombreC;
    private javax.swing.JTextField tf_NumeroDTele;
    // End of variables declaration//GEN-END:variables
    private int Orden = 7;
}
